---
# tasks file for setup-apache-role
- name: install httpd
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: install apache
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Dibian"
  notify: start apache2 service

- name: copy file index.html
  copy:
    src: /home/hari/index.html
    dest: /var/www/html
    mode: 0666
